"""Runs the pipeline's Stage 1 (normalisation) + Stage 2 (detection) +
Stage 3 (resolution) against the 134-case labeled test set and reports
real precision/recall/F1 — per entity type, never one aggregate number;
both the strict (primary) and relaxed (diagnostic) matching rule; a
PERSON recall breakdown by naming convention; and the concrete failure
cases behind every number.

Nothing in EVAL_RESULTS.md is invented or estimated — it is this script's
printed output, copied in.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from pii_redaction.evaluation import EvalResult, evaluate_dataset, f1, precision, recall  # noqa: E402
from pii_redaction.normalise import normalise  # noqa: E402
from pii_redaction.pipeline import default_detectors  # noqa: E402
from pii_redaction.resolution import resolve  # noqa: E402

DATA_PATH = Path(__file__).resolve().parent.parent / "tests" / "data" / "labeled_pii_test_set.jsonl"
REPORT_PATH = Path(__file__).resolve().parent.parent / "EVAL_RESULTS.md"


def load_records() -> list[dict]:
    records = []
    with open(DATA_PATH, encoding="utf-8") as f:
        for line in f:
            records.append(json.loads(line))
    return records


def fmt(x: float | None) -> str:
    return f"{x:.3f}" if x is not None else "-"


def render_confusion_table(per_type: dict) -> str:
    lines = ["| Entity type | TP | FP | FN | Precision | Recall | F1 |", "|---|---|---|---|---|---|---|"]
    for entity_type in sorted(per_type):
        c = per_type[entity_type]
        lines.append(
            f"| {entity_type} | {c.tp} | {c.fp} | {c.fn} | {fmt(precision(c))} | {fmt(recall(c))} | {fmt(f1(c))} |"
        )
    return "\n".join(lines)


def render_person_category_table(person_by_category: dict) -> str:
    lines = [
        "| Naming convention | TP | FN | Recall |",
        "|---|---|---|---|",
    ]
    for category in sorted(person_by_category):
        c = person_by_category[category]
        lines.append(f"| {category} | {c.tp} | {c.fn} | {fmt(recall(c))} |")
    return "\n".join(lines)


def render_failures(result: EvalResult, limit: int | None = None) -> str:
    failures = result.failures if limit is None else result.failures[:limit]
    lines = []
    for f_ in failures:
        if f_.kind == "FN":
            lines.append(f"- **FN** [{f_.case_id}/{f_.category}] {f_.entity_type} gold {f_.span_text!r} not detected — in: {f_.text!r}")
        else:
            lines.append(f"- **FP** [{f_.case_id}/{f_.category}] {f_.entity_type} spuriously detected {f_.span_text!r} — in: {f_.text!r}")
    return "\n".join(lines) if lines else "(none)"


def main() -> None:
    records = load_records()
    detectors = default_detectors()

    def predict(text: str):
        # Gold offsets in the JSONL are computed against the original,
        # unnormalised sentence text. normalise() must be a no-op on every
        # case in this dataset (plain ASCII, no irregular whitespace) for
        # those offsets to still line up against normalised_text below —
        # asserted, not assumed, since a silent mismatch here would corrupt
        # every number in this report.
        normalised_text = normalise(text)
        assert normalised_text == text, (
            f"normalise() changed test-set text ({text!r} -> {normalised_text!r}); "
            "gold offsets would no longer line up — fix the test case, don't skip this check"
        )
        raw = [e for d in detectors for e in d.detect(normalised_text)]
        return resolve(raw)

    strict = evaluate_dataset(records, predict, "strict")
    relaxed = evaluate_dataset(records, predict, "relaxed")

    print(f"Loaded {len(records)} cases from {DATA_PATH.name}\n")
    print("STRICT matching (primary, reported number)")
    print(render_confusion_table(strict.per_type))
    print()
    print("RELAXED matching (diagnostic companion)")
    print(render_confusion_table(relaxed.per_type))
    print()
    print("PERSON recall by naming convention (strict matching):")
    print(render_person_category_table(strict.person_by_category))
    print()
    print(f"Total failures under strict matching: {len(strict.failures)}")
    for f_ in strict.failures:
        print(f"  {f_.kind} [{f_.case_id}/{f_.category}] {f_.entity_type} {f_.span_text!r}")

    report = f"""# Session 4 Evaluation Results

Generated by `scripts/evaluate.py` against the {len(records)}-case labeled
test set at `tests/data/labeled_pii_test_set.jsonl`. Every number below is
this script's actual output — nothing here is estimated or invented.

Matching rule: see `src/pii_redaction/evaluation.py` module docstring.
**Strict** (exact character-offset + type match) is the primary, reported
metric. **Relaxed** (any span overlap of the same type) is shown alongside
purely to characterize *why* strict recall is lower than it might look —
never as the headline number.

## STRICT matching (primary)

{render_confusion_table(strict.per_type)}

## RELAXED matching (diagnostic)

{render_confusion_table(relaxed.per_type)}

## PERSON recall by naming convention (strict matching)

{render_person_category_table(strict.person_by_category)}

Restricted to the dedicated `person_*` categories (one clean PERSON
mention per sentence) rather than the `mixed` category, so each recall
number is attributable to a single naming convention rather than diluted
by multi-entity sentences.

## All failures under strict matching ({len(strict.failures)} total)

{render_failures(strict)}
"""
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"\nWrote {REPORT_PATH}")


if __name__ == "__main__":
    main()
